"""Assemble the Vietnamese final report strictly from recorded evidence."""
from pathlib import Path
import csv,json
p=Path('reports/BAO_CAO_LAB21.md');base=p.read_text().split('<!-- RESULTS -->')[0]
base=base.replace('Báo cáo đang được xây dựng từ thực nghiệm thật. Chưa công bố cấu hình cuối cùng hoặc điểm số trước khi hoàn thành kiểm tra tương ứng. Dữ liệu synthetic chỉ được dùng trong regression tests.','Đã chạy thực nghiệm trên dữ liệu thật, xuất đủ năm sequence và tính TrackEval cho video_1. Dữ liệu synthetic chỉ được dùng trong regression tests, không đưa vào kết quả lab.')
env=json.loads(Path('artifacts/environment.json').read_text());data=json.loads(Path('artifacts/scene_analysis/dataset_metadata.json').read_text());configs=json.loads(Path('reports/selected_configs.json').read_text());candidates=json.loads(Path('artifacts/metrics/video_1_candidates.json').read_text())
with Path('artifacts/metrics/video_1_metrics.csv').open() as f:scores=next(csv.DictReader(f))
with Path('reports/experiment_log.csv').open() as f:experiments=list(csv.DictReader(f))
parts=['<!-- RESULTS -->','## Môi trường và dữ liệu thật',f'Python {env["python"]}; {env["platform"]}; RAM 16 GiB. Detector dùng {env["detector_device"]}; encoder Re-ID dùng CPU FP32. PyTorch {env["torch"]}.', '| Thành phần | Phiên bản |','|---|---|']
parts += [f'| {k} | {v} |' for k,v in env['versions'].items()]
parts += [f'\nTrackEval commit: `{env["trackeval_commit"]}`. Script `patch_trackeval.py` chỉ thay alias np.float/np.int/np.bool đã bị loại bỏ bằng built-in tương ứng, không đổi logic metric. BoxMOT 25.0.0 cài từ PyPI dùng TrackerSpec và configure_reid(ReIDEncoderSpec); không giả định API nhánh master giống wheel đã cài. Cả năm tracker qua smoke test; ba tracker appearance xác nhận encoder đã chạy và OSNet nạp đủ 565/565 tensors.','\n| Checkpoint | SHA256 |','|---|---|']
parts += [f'| {k} | `{v}` |' for k,v in env['weights'].items()]
parts += ['\nNguồn dữ liệu là archive Drive được chỉ định (647 MB), tải công khai thành công; SHA256 và URL trong `artifacts/dataset_source.json`. Tất cả JPG được đọc kiểm tra; frame đặt tên số liên tục bắt đầu từ1.','\n| Video | Frames | Kích thước H×W | FPS gốc |','|---|---|---|---|']
for name,d in data.items():parts.append(f'| {name} | {d["frames"]} | {d["dimensions"]} | {d["fps"] if d["fps"] else "Không có metadata đáng tin cậy"} |')
parts += ['\nvideo_1 là MOT17-02-FRCNN, GT gốc có9cột, phủframes1–600. Có '+str(data['video_1']['gt_inspection']['valid_person_rows'])+' hàng pedestrian hợp lệ trước preprocessing. Không thay missing labels bằng negative GT. Các class/zero-marked objects được giữ nguyên để TrackEval xử lý.','## Phân tích cảnh và giả thuyết trước thí nghiệm',Path('artifacts/scene_analysis/scene_analysis.md').read_text().replace('# Quan sát cảnh trước thí nghiệm',''), '## Baseline ByteTrack',Path('artifacts/scene_analysis/baseline_observation.md').read_text().replace('# Baseline ByteTrack — video_1 frames 1–150',''),'\nỞ baseline, áo tím ID3 và áo đỏ ID2 giữ danh tính tại1/75/150. Màu phụ thuộc ID, visualization không phát sinh ID mới. Notebook đã chạy end-to-end với kernel cv_robotics_lab21, ba câu đúng/sai và YOLO inference ảnh thật.','## Kết quả thí nghiệm và lựa chọn',f'Đã hoàn thành {len(experiments)} run được ghi trong `reports/experiment_log.csv`. Manifest metadata, model hashes, Re-ID state và output hashes được lưu trong `artifacts/experiment_manifest.json`. Tất cả so sánh đầu dùngframes1–150; verification dùng301–450, khởi tạo tracker mới tại đầu mỗi đoạn. Video_1 bổ sung bảy run đủ600frames. Không so sánh ID numeric giữa hai tracker như thể đó là cùng danh tính.',Path('reports/selection_observations.md').read_text().replace('# Ghi nhận lựa chọn — sau so sánh tracker và confidence',''),'## Bảng định lượng video_1', 'Tất cả giá trị HOTA/MOTA/IDF1 sau đây là phần trăm, từ TrackEval chạy với GT thật trên đủ600frames. Các run có cùng detector/640/class, preprocessing và phạm vi; chỉ thaytracker/conf/IoU theo từng phép so sánh.', '| Tracker | Conf | NMS IoU | HOTA | MOTA | IDF1 | IDSW | FP | FN |','|---|---|---|---|---|---|---|---|---|']
for r in candidates:parts.append(f'| {r["tracker"]} | {r["conf"]:.2f} | {r["iou"]:.2f} | {r["HOTA"]:.4f} | {r["MOTA"]:.4f} | {r["IDF1"]:.4f} | {r["IDSW"]} | {r["FP"]} | {r["FN"]} |')
parts += [f'\nRun final được đánh giá riêng: **HOTA {float(scores["HOTA"]):.4f}, MOTA {float(scores["MOTA"]):.4f}, IDF1 {float(scores["IDF1"]):.4f}**. Nguồn: `artifacts/metrics/video_1_metrics.csv`, provenance GT/prediction SHA256 trong `video_1_evaluation.md`. DetA = {float(scores["DetA"]):.4f}, AssA = {float(scores["AssA"]):.4f}.','\nBoTSORT0,15/0,50 cải thiện association/identity so với ByteTrack0,15/0,50 nhưng có nhiều FN hơn nên MOTA thấp hơn. Chọn theo mục tiêu ưu tiên giữID; không kết luận tốt hơn trên mọi metric. Điểm tuyệt đối thấp và FN rất lớn: pipeline cố định YOLO26n640 cùng ngưỡng khởi tạo tracker mặc định chưa bao phủ người nhỏ/che khuất. Re-ID không sinh detections bị thiếu. Đây là hạn chế thật, không sửa metric hoặc đổi model để che giấu.','## Cấu hình cuối và kết quả full sequence','| Video | Tracker | Conf | IoU | Frames | Dòng MOT | Lý do |','|---|---|---|---|---|---|---|']
for name,c in configs.items():
    m=json.loads(Path(c['full_sequence_metadata']).read_text());n=sum(1 for _ in Path(f'runs/nop_bai/{name}.txt').open());parts.append(f'| {name} | {c["tracker"]} | {c["conf"]:.2f} | {c["iou"]:.2f} | {m["frames_processed"]} | {n} | {c["reason"]} |')
parts += ['\nSố dòng và số IDs là thống kê predictions, không phải accuracy. Video_2–5 chỉ đánh giá bằng quan sát, không có HOTA/MOTA/IDF1. Năm final run không dùng max-frames. Frame không cótracks không códòngMOT.','\nMOT dùng frame/ID dương và gốc bbox(1,1). Development runs ban đầu được hiệu chỉnh left/top+1 theo tài liệu chính thức TrackEval trước đánh giá; width/height/confidence/ID không đổi. Run final xuất trực tiếp đúng convention, không áp dịch lần hai.','\nNgưỡng association giữ nguyên defaults BoxMOT: ByteTrack track_thresh=0,60, BoTSORT new_track_thresh≈0,62465 và track_high_thresh≈0,62969 (artifacts/final_video_qa.json). Vì vậy hạ detector confidence không tự tạo track mới cho mọi detection yếu; điều này giải thích lợi ích coverage hạn chế. Không thay các ngưỡng đó trong thí nghiệm.', '## Kiểm thử, đóng gói và tái lập','20 regression tests đã pass: thứ tự frames, Zip Slip, IoU edge cases, NMS overlap, năm tracker, state/ID, MOT invalid rows, TrackEval perfect/missing/ID-switch/misalignment và missing submission provenance. Tests synthetic không được dùng làm kết quả thật.','\nValidator kiểm tra10cột, finite values, bbox positive, IDs, duplicate(frame,ID), thứ tựframes, source/model/hash, selected configs, Re-ID state và toàn bộ inputframes. ZIP chỉ chứavideo_1.txt–video_5.txt vàBAO_CAO_LAB21.md; testzip và so sánhbytes với nguồn.','\nTái lập: làm theo README từ venv và requirements-lock.txt; tải/check dữ liệu, chạy notebook, tracker/conf/IoU sweeps, render comparisons, chọn cấu hình bằng evidence; chạy `LAB_DATA=... .venv/bin/python scripts/run_selected.py`, evaluate_video1.py, validate_submission.py, prepare_submission.py. Các kết quả có sẵn được kiểm tra hash trước resume, không ghi đè âm thầm.','\nRepository PRIVATE: https://github.com/kevindao94work/cv-robotics-lab21; ownerkevindao94work; branchmain; remoteorigin. CP0–CP5 có commit/push và đối chiếuSHA; bảngcheckpoint và receipts trongreports.','## Thảo luận và kết luận','Re-ID hữu ích cho một số đoạn di chuyển/che khuất ởvideo_3 và cải thiện identity tổng thể ởvideo_1. Ởvideo_4, appearance vẫn đổiID người áo trắng màByteTrack giữ; ởvideo_2/5, detections người nhỏ là giới hạn lớn hơn matching. Reflection và ánh sáng yếu là rủi ro cảnh quan sát được; không khẳng định chúng gâyFP cụ thể nếu evidence không chứng minh.','\nHai đoạn150frames/video không bao quát mọi tình huống. Việc chọnvideo_1 dựa trên cùng GT dùng đánh giá tạo nguy cơ overfit; không có tập test độc lập. Các tracker giữ cấu hìnhassociation mặc định, chỉ khảo sát detectorconf/NMSIoU vàtracker theo guide. Không tuyên bố tracker tốt nhất toàn cục; kết luận giới hạn ở dữ liệu và cấu hình đã chạy.']
import re
text=base+'\n\n'+'\n\n'.join(parts)+'\n'
text=text.replace('|\n\n|','|\n|')
text=re.sub(r'(conf|iou|frames|frame|tại|qua|từ|đến|giữ|đổi|hoặc|ảnh|xuống|đạt|sweeps|trung gian|chênh lệch|BoTSORT|ByteTrack|HOTA|IDF1)(?=\d)',r'\1 ',text,flags=re.I)
text=re.sub(r'(\d)(frames|frame|cột)',r'\1 \2',text)
text=text.replace('giữID','giữ ID').replace('đổiID','đổi ID').replace('sangID','sang ID').replace('YOLO26n640','YOLO26n 640').replace('cótracks','có tracks').replace('códòngMOT','có dòng MOT').replace('bbox(1,1)','bbox (1,1)').replace('left/top+1','left/top +1')
text=text.replace('Ởvideo_', 'Ở video_').replace('ởvideo_', 'ở video_').replace('thứ tựframes','thứ tự frames').replace('thaytracker','thay tracker')
text=re.sub(r'\n{3,}','\n\n',text)
p.write_text(text)
